apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: talk2linojoy/product-service-55 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080 # The port that the container is running on in the cluster